export default [
  {
    name: 'id',
    required: false,
    label: 'User ID',
    field: 'id',
    sortable: true,
  },
  {
    name: 'username',
    required: false,
    label: 'Username',
    field: 'username',
    align: 'left',
    sortable: true,
  },
    {
      name: 'firstName',
      required: false,
      label: 'First Name',
      field: 'firstName',
      align: 'left',
      sortable: true,
    },
    {
      name: 'middleName',
      required: false,
      label: 'Middle Name',
      field: 'middleName',
      align: 'left',
      sortable: true,
    },
    {
      name: 'lastName',
      required: false,
      label: 'Last Name',
      field: 'lastName',
      align: 'left',
      sortable: true,
    },
    {
      name: 'group',
      required: false,
      label: 'Group',
      field: 'group',
      sortable: true,
    },
    {
      name: 'isPUM',
      required: false,
      label: 'Is Under Monitoring',
      format: (val: number) => `${!!val ? '✔ Yes' : '❌ No'}`,
      field: 'isPUM',
      sortable: true,
    },
    {
      name: 'isPUI',
      required: false,
      label: 'Is Under Investigation',
      format: (val: number) => `${!!val ? '✔ Yes' : '❌ No'}`,
      field: 'isPUI',
      sortable: true,
    },
    {
      name: 'isVaccinated',
      required: false,
      label: 'Is Vaccinated',
      format: (val: number) => `${!!val ? '✔ Yes' : '❌ No'}`,
      field: 'isVaccinated',
      sortable: true,
    },
    {
      name: 'isVaccineReady',
      required: false,
      label: 'Vaccine Readiness',
      field: 'isVaccineReady',
      sortable: true,
    },
    {
      name: 'vaccineManufacturer',
      required: false,
      label: 'Vaccine Manufacturer',
      field: 'vaccineManufacturer',
      sortable: true,
    },
    {
      name: 'profession',
      required: false,
      label: 'Profession',
      field: 'profession',
      sortable: true,
    },
    {
      name: 'otherProfession',
      required: false,
      label: 'Profession (Other)',
      field: 'otherProfession',
      sortable: true,
    },
    {
      name: 'dosageNumber',
      required: false,
      label: 'Dosage Number',
      field: 'dosageNumber',
      sortable: true,
    }
]
