version: "3"
services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "3000:3000"
    command: nodemon -L
    volumes:
      - .:/app/
      - /app/node_modules
  
  postgres:
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres