# This is a basic workflow to help you get started with Actions

name: Continuous Integration (CI)

# Controls when the action will run. 
on:
    push:
      branches: [main]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out master branch
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
          architecture: x64 

      - name: Install Quasar CLI 
        run: npm install -g @quasar/cli

      - name: Install Cordova
        run: npm install -g cordova
          
      - name: Install packages
        run: npm install

      - name: Perform build/compile step
        run: npx quasar build -m cordova -T android

      - name: List build artifacts
        run: |
          cd ./dist/cordova/android
          ls -R
        
#     - name: Create and upload release
#       uses: softprops/action-gh-release@v1
#       if: startsWith(github.ref, 'refs/tags/')
#       with:
#         files: |
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}