
# This is a basic workflow to help you get started with Actions

name: Automated Testing

# Controls when the action will run. 
on:
    pull_request:
      branches: [main]
    push:
      branches: [main]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out master branch
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.8.0
          architecture: x64 

      - name: Install packages
        run: cd server && npm install

      - name: Install Mocha testing suite
        run: npm install --global mocha
      
      - name: Compile TypeScript
        run: cd server && tsc

      - name: Run tests
        run: cd server && npm run test
        env:
          DB_URL: ${{ secrets.DB_URL }}

