module.exports = {
	"username": "",
	"password": "",
	"email": "",
	"category": "01 - Health Care Worker",
	"categoryID": "PRC ID",
	"philHealthID": "string",
	"lastName": "string",
	"firstName": "string",
	"middleName": "string",
	"suffix": "string",
	"contactNumber": "09260729017",
	"fullAddress": "string",
	"province": "string",
	"municipalityOrCity": "string",
	"barangay": "string",
	"sex": "03 - Not to Disclose",
	"dateOfBirth": "2001/12/29",
	"civilStatus": "01 - Single",
	"employed": "01 - Government Employed",
	"profession": "12 - Physician",
	"otherProfession": "string",
	"employerContactNumber": "09260729017",
	"directCOVID": true,
	"pregnancyStatus": false,
	"withAllergy": false,
	"allergy": "string",
	"withComorbidities": false,
	"comorbidity": "01 - Hypertension",
	"covidHistory": false,
	"consentForDataCollection": "01 - Yes",
	"consentForVaccination": "01 - Yes"
}